apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hydra.fullname" . }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
type: Opaque
data:
  secretsSystem: {{ include "hydra.secrets.system" . | quote }}
  secretsCookie: {{ include "hydra.secrets.cookie" . | quote }}
  dsn: {{ include "hydra.dsn" . | quote }}
