version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run: curl -L https://git.io/get_helm.sh | bash
      - run: helm lint ./helm/charts/oathkeeper/
      - run: helm lint ./helm/charts/hydra/
      - run: helm lint ./helm/charts/example-idp/

  test:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Install kubectl"
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv kubectl /usr/bin/kubectl
      - run:
          name: "Set up kind and helm"
          command: |
            bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

            curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind

            kind --loglevel=debug create cluster

            export KUBECONFIG=$(kind get kubeconfig-path)
            echo 'export KUBECONFIG=$KUBECONFIG' >> $BASH_ENV

            curl -L https://git.io/get_helm.sh | bash

            kubectl create -f .cricleci/rbac-config.yaml
            helm init --wait --service-account tiller
      - run: .circleci/helm-test.sh oathkeeper
      - run: .circleci/helm-test.sh hydra

  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run: curl -L https://git.io/get_helm.sh | bash
      - run: helm init --client-only
      - run: helm package -d docs/helm/charts/ ./helm/charts/oathkeeper/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm package -d docs/helm/charts/ ./helm/charts/hydra/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm package -d docs/helm/charts/ ./helm/charts/example-idp/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm repo index docs/helm/charts/
      - run: git config --global user.email "hi@ory.sh"
      - run: git config --global user.name "ORY Continuous Integration"
      - run: git checkout -b make-release HEAD
      - run: git add -A
      - run: git commit -a -m "Release $CIRCLE_TAG"
      - run: git push origin HEAD:master

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
