version: 2.1
jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run: curl -L https://git.io/get_helm.sh | bash
      - run: helm lint ./helm/charts/oathkeeper/
      - run: helm lint ./helm/charts/hydra/
      - run: helm lint ./helm/charts/example-idp/

  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - setup_remote_docker
      - run: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - run: chmod +x ./kubectl
      - run: mv kubectl /go/bin/kubectl
      - run: curl -L https://git.io/get_helm.sh | bash
      - run: make kind-start
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export KUBECONFIG="$(kind get kubeconfig-path)"' >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run: echo KUBECONFIG
      - run: kubectl config current-context
      - run: helm init
      - run: .circleci/helm-test.sh oathkeeper
      - run: .circleci/helm-test.sh hydra

  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/k8s
    steps:
      - checkout
      - run: curl -L https://git.io/get_helm.sh | bash
      - run: helm init --client-only
      - run: helm package -d docs/helm/charts/ ./helm/charts/oathkeeper/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm package -d docs/helm/charts/ ./helm/charts/hydra/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm package -d docs/helm/charts/ ./helm/charts/example-idp/ --version `echo $CIRCLE_TAG | sed s/v//g`
      - run: helm repo index docs/helm/charts/
      - run: git config --global user.email "hi@ory.sh"
      - run: git config --global user.name "ORY Continuous Integration"
      - run: git checkout -b make-release HEAD
      - run: git add -A
      - run: git commit -a -m "Release $CIRCLE_TAG"
      - run: git push origin HEAD:master

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - lint:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - lint
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
