apiVersion: v1
entries:
  oathkeeper:
  - apiVersion: v1
    appVersion: v0.16.0-beta.4_oryOS.12
    created: "2019-06-22T19:18:36.68204412Z"
    description: A Helm chart for deployoing ORY Oathkeeper in Kubernetes
    digest: 56bdbdaaabf1ec25598fa4aa7e58e8a0627052cba280b76787dec009529fe7d9
    home: https://www.ory.sh/
    keywords:
    - zero-trust
    - beyond-corp
    - access-control
    - reverse-proxy
    - nginx
    - envoy
    - ambassador
    - auth-filter
    maintainers:
    - email: hi@ory.sh
      name: ORY Team
      url: https://www.ory.sh/
    name: oathkeeper
    sources:
    - https://github.com/ory/oathkeeper
    - https://github.com/ory/k8s
    urls:
    - oathkeeper-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: v0.16.0-beta.4
    created: "2019-06-22T19:18:36.681565345Z"
    description: A Helm chart for deployoing ORY Oathkeeper in Kubernetes
    digest: 49a9449435aade826fd38683373930863fe895a1a5b39fb0472c56d8c1a5ea7a
    home: https://www.ory.sh/
    keywords:
    - zero-trust
    - beyond-corp
    - access-control
    - reverse-proxy
    - nginx
    - envoy
    - ambassador
    - auth-filter
    maintainers:
    - email: hi@ory.sh
      name: aeneasr
      url: https://www.ory.sh/
    name: oathkeeper
    sources:
    - https://github.com/ory/oathkeeper
    - https://github.com/ory/k8s
    urls:
    - oathkeeper-0.0.5.tgz
    version: 0.0.5
generated: "2019-06-22T19:18:36.680881965Z"
